"""empty message

Revision ID: 427b5c37a1ab
Revises: 
Create Date: 2020-12-15 22:45:34.073772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427b5c37a1ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
