"""empty message

Revision ID: d60ef3b0bdce
Revises: 427b5c37a1ab
Create Date: 2020-12-15 23:02:48.118115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60ef3b0bdce'
down_revision = '427b5c37a1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_cent', sa.Integer(), nullable=True),
    sa.Column('all_money', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('password', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('passport', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('adress', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('money_amount', sa.Integer(), nullable=True),
    sa.Column('telephone_number', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('super_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_sum', sa.Integer(), nullable=True),
    sa.Column('current_sum', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bank_id'], ['banks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sum', sa.BigInteger(), nullable=True),
    sa.Column('credit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_id'], ['credits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('credits')
    op.drop_table('users')
    op.drop_table('banks')
    # ### end Alembic commands ###
